services:
  db:
    image: postgres:15
    container_name: tryton-postgres
    environment:
      - POSTGRES_PASSWORD=tryton123
      - POSTGRES_DB=tryton
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tryton-net

  tryton:
    image: tryton/tryton:latest
    container_name: tryton-server
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=tryton
      - DB_PASSWORD=tryton123
    volumes:
      - tryton_data:/var/lib/trytond
      - ./trytond.conf:/etc/trytond.conf:ro
    networks:
      - tryton-net

volumes:
  pgdata:
  tryton_data:

networks:
  tryton-net:
