version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tryton
      POSTGRES_USER: tryton
      POSTGRES_PASSWORD: tryton
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tryton"]
      interval: 5s
      timeout: 5s
      retries: 5

  tryton-init:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_USER: tryton
      DB_PASSWORD: tryton
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_NAME: tryton
    volumes:
      - ./trytond.conf:/etc/trytond.conf:ro
    command: trytond-admin -d tryton --all -c /etc/trytond.conf
    restart: "no"

  tryton-server:
    build: .
    depends_on:
      - tryton-init
    environment:
      DB_USER: tryton
      DB_PASSWORD: tryton
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_NAME: tryton
    ports:
      - "8000:8000"
    volumes:
      - ./trytond.conf:/etc/trytond.conf:ro
    command: /entrypoint.sh trytond -c /etc/trytond.conf
    restart: unless-stopped

  tryton-cron:
    build: .
    depends_on:
      - tryton-server
    environment:
      DB_USER: tryton
      DB_PASSWORD: tryton
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_NAME: tryton
    volumes:
      - ./trytond.conf:/etc/trytond.conf:ro
    command: trytond-cron -d tryton -c /etc/trytond.conf
    restart: unless-stopped

volumes:
  pgdata:
